trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    sudo apt-get update
    sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    sudo apt-get install -y r-base
    Rscript -e 'install.packages("rsconnect", repos="https://cloud.r-project.org")'
    Rscript -e 'rsconnect::setAccountInfo(name=Sys.getenv("ramkiapps"), token=Sys.getenv("94A259A8B02489BAFC5E2CE3442D164C"), secret=Sys.getenv("0rZk4dmGFbNu8EZlcbdCNqt6SG0axN/TdUt0sMTK"))'
    Rscript -e 'rsconnect::deployApp(appDir = "C:/Users/admin/source/repos/demand Forecasting", appName = "my-shiny-app", account = Sys.getenv("SHINYAPPS_ACCOUNT"))'
  displayName: 'Deploy to shinyapps.io'
  env:
    SHINYAPPS_ACCOUNT: $(ramkiapps)
    SHINYAPPS_TOKEN: $(94A259A8B02489BAFC5E2CE3442D164C)
    SHINYAPPS_SECRET: $(0rZk4dmGFbNu8EZlcbdCNqt6SG0axN/TdUt0sMTK)

