trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  CRAN: 'https://cloud.r-project.org'

steps:
  # Step 1: Install R
  - task: UsePythonVersion@0  # Needed for rsconnect's dependencies
    inputs:
      versionSpec: '3.x'
  - bash: |
      sudo apt update
      sudo apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
      sudo apt install -y r-base
      R --version
    displayName: 'Install R'

  # Step 2: Install R packages
  - bash: |
      Rscript -e "install.packages(c('shiny', 'forecast', 'rsconnect'), repos='${CRAN}')"
    displayName: 'Install R packages'

  # Step 3: Run Forecast Script (e.g., test model)
  - bash: |
      Rscript forecast.R  # or any test/build script
    displayName: 'Run Forecast'

  # Step 4: Deploy to shinyapps.io
  - bash: |
      echo 'Setting up rsconnect account...'
      Rscript -e "rsconnect::setAccountInfo(name='azureprojects', token='$()', secret='$(SHINYAPPS_SECRET)')"
      Rscript -e "rsconnect::deployApp(appDir = '.', appName = 'your-app-name', account = 'yourname')"
    displayName: 'Deploy to shinyapps.io'
